{
  "startTime": 1674253021120,
  "endTime": 1674253022142,
  "originalSmells": [
    {
      "rule": "tarSomethingRmTheSomething",
      "position": {
        "lineStart": 8,
        "lineEnd": 8,
        "columnStart": 4,
        "columnEnd": 54
      }
    },
    {
      "rule": "tarSomethingRmTheSomething",
      "position": {
        "lineStart": 12,
        "lineEnd": 12,
        "columnStart": 4,
        "columnEnd": 55
      }
    }
  ],
  "repairedSmells": [],
  "repairedDockerfile": "FROM pure/python:3.7-cuda10.0-base\n\nWORKDIR /app\n\n# Download the pretrained models. The --no-same-owner flag\n# is to prevent an error message when tar runs as root.\n# See https://superuser.com/questions/1435437/how-to-get-around-this-error-when-untarring-an-archive-tar-cannot-change-owner\nRUN wget https://storage.googleapis.com/sfr-factcc-data-research/factcc-checkpoint.tar.gz\nRUN tar -xvzf factcc-checkpoint.tar.gz --no-same-owner && rm factcc-checkpoint.tar.gz\nRUN rm factcc-checkpoint.tar.gz\n\nRUN wget https://storage.googleapis.com/sfr-factcc-data-research/factccx-checkpoint.tar.gz\nRUN tar -xvzf factccx-checkpoint.tar.gz --no-same-owner && rm factccx-checkpoint.tar.gz\nRUN rm factccx-checkpoint.tar.gz\n\n# The default version of cryptacular, 1.6.0, which is installed as a dependency of\n# a package in requirements.txt, gave us errors installing:\n# ERROR: Could not build wheels for cryptacular which use PEP 517 and cannot be installed directly\nRUN pip install --no-cache-dir cryptacular==1.5.1\n\n# Clone the code and install the dependencies\nRUN git clone https://github.com/salesforce/factCC && \\\n    cd factCC && \\\n    git checkout 40a8a5684ec7131bfc92396d9b7f236f80095665 && \\\n    pip install --no-cache-dir -r requirements.txt\n\n# Install extra dependencies\nRUN pip install --no-cache-dir wandb==0.11.2\n\n# Copy the scoring code\nCOPY src/run_test.py factCC/modeling/run_test.py\n\n# Run warmup code\nCOPY scripts/warmup.sh warmup.sh\nRUN sh warmup.sh"
}