{"repository":"https://github.com/mlf-core/mlf-core","dockerfilePath":"Dockerfile","startTime":1673088613341,"endTime":1673088642669,"clone":{"startTime":1673088613342,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/mlf-core/mlf-core'...\n","error":null,"endTime":1673088615216,"commit":"cea155595df95d1d22473605d29813f5d698d635"},"originalBuild":{"startTime":1673088615303,"endTime":1673088642588,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t mlf-core:latest -f /tmp/dinghy-analysis/mlf-core/mlf-core/Dockerfile ."},"stdout":"Sending build context to Docker daemon  33.73MB\r\r\nStep 1/5 : FROM python:3.8.1-alpine\n3.8.1-alpine: Pulling from library/python\nc9b1b535fdd9: Pulling fs layer\n2cc5ad85d9ab: Pulling fs layer\n61614c1a5710: Pulling fs layer\n0522d30cde10: Pulling fs layer\n938854eeb444: Pulling fs layer\n0522d30cde10: Waiting\n938854eeb444: Waiting\n2cc5ad85d9ab: Verifying Checksum\n2cc5ad85d9ab: Download complete\nc9b1b535fdd9: Verifying Checksum\nc9b1b535fdd9: Download complete\nc9b1b535fdd9: Pull complete\n0522d30cde10: Verifying Checksum\n2cc5ad85d9ab: Pull complete\n61614c1a5710: Verifying Checksum\n61614c1a5710: Download complete\n938854eeb444: Verifying Checksum\n938854eeb444: Download complete\n61614c1a5710: Pull complete\n0522d30cde10: Pull complete\n938854eeb444: Pull complete\nDigest: sha256:50c60fffe5451e18af2c53d75b6864b5a0fcb458e239302cc218064ce4946ce7\nStatus: Downloaded newer image for python:3.8.1-alpine\n ---> a1cd5654cf3c\nStep 2/5 : RUN apk update\n ---> Running in 0f97aa0b5bfd\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz\nv3.11.13-12-g2cfa91a2b4 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]\nv3.11.11-124-gf2729ece5a [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]\nOK: 11291 distinct packages available\nRemoving intermediate container 0f97aa0b5bfd\n ---> 5b92f77563d4\nStep 3/5 : RUN apk add make automake gcc g++ git\n ---> Running in fd87a493f9c8\n(1/24) Upgrading musl (1.1.24-r0 -> 1.1.24-r3)\n(2/24) Installing perl (5.30.3-r0)\n(3/24) Installing automake (1.16.1-r0)\n(4/24) Installing libgcc (9.3.0-r0)\n(5/24) Installing libstdc++ (9.3.0-r0)\n(6/24) Installing binutils (2.33.1-r1)\n(7/24) Installing gmp (6.1.2-r1)\n(8/24) Installing isl (0.18-r0)\n(9/24) Installing libgomp (9.3.0-r0)\n(10/24) Installing libatomic (9.3.0-r0)\n(11/24) Installing mpfr4 (4.0.2-r1)\n(12/24) Installing mpc1 (1.1.0-r1)\n(13/24) Installing gcc (9.3.0-r0)\n(14/24) Installing musl-dev (1.1.24-r3)\n(15/24) Installing libc-dev (0.7.2-r0)\n(16/24) Installing g++ (9.3.0-r0)\n(17/24) Installing nghttp2-libs (1.40.0-r1)\n(18/24) Installing libcurl (7.79.1-r0)\n(19/24) Installing pcre2 (10.34-r1)\n(20/24) Installing git (2.24.4-r0)\n(21/24) Installing perl-error (0.17028-r0)\n(22/24) Installing perl-git (2.24.4-r0)\n(23/24) Installing git-perl (2.24.4-r0)\n(24/24) Installing make (4.2.1-r2)\nExecuting busybox-1.31.1-r9.trigger\nOK: 238 MiB in 58 packages\nRemoving intermediate container fd87a493f9c8\n ---> ecb48e04a620\nStep 4/5 : RUN pip install mlf-core\n ---> Running in 4c40c0405416\nCollecting mlf-core\n  Downloading mlf_core-1.11.4-py3-none-any.whl (6.0 MB)\nCollecting click<9.0.0,>=7.1.2\n  Downloading click-8.1.3-py3-none-any.whl (96 kB)\nCollecting questionary<2.0.0,>=1.9.0\n  Downloading questionary-1.10.0-py3-none-any.whl (31 kB)\nCollecting GitPython<4.0.0,>=3.1.15\n  Downloading GitPython-3.1.30-py3-none-any.whl (184 kB)\nCollecting ruamel.yaml<0.18.0,>=0.17.4\n  Downloading ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)\nCollecting PyGithub<2.0.0,>=1.54.1\n  Downloading PyGithub-1.57-py3-none-any.whl (297 kB)\nCollecting mlflow<2.0.0,>=1.15.0\n  Downloading mlflow-1.30.0-py3-none-any.whl (17.0 MB)\nCollecting cookiecutter<2.0.0,>=1.7.2\n  Downloading cookiecutter-1.7.3-py2.py3-none-any.whl (34 kB)\nCollecting cryptography<36.0.0,>=3.4.7\n  Downloading cryptography-35.0.0.tar.gz (559 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'error'\n\u001b[91m  ERROR: Command errored out with exit status 1:\n   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-cqcmhiwj/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '\"'\"'PyPy'\"'\"'' 'setuptools-rust>=0.11.4'\n       cwd: None\n  Complete output (108 lines):\n  Collecting setuptools>=40.6.0\n    Downloading setuptools-65.6.3-py3-none-any.whl (1.2 MB)\n  Collecting wheel\n    Downloading wheel-0.38.4-py3-none-any.whl (36 kB)\n  Collecting cffi>=1.12\n    Downloading cffi-1.15.1.tar.gz (508 kB)\n  Collecting setuptools-rust>=0.11.4\n    Downloading setuptools_rust-1.5.2-py3-none-any.whl (23 kB)\n  Collecting pycparser\n    Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)\n  Collecting semantic-version<3,>=2.8.2\n    Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)\n  Collecting typing-extensions>=3.7.4.3\n    Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)\n  Building wheels for collected packages: cffi\n    Building wheel for cffi (setup.py): started\n    Building wheel for cffi (setup.py): finished with status 'error'\n    ERROR: Command errored out with exit status 1:\n     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /tmp/pip-wheel-3eouxfvm\n         cwd: /tmp/pip-install-1zk5v_9p/cffi/\n    Complete output (36 lines):\n    running bdist_wheel\n    running build\n    running build_py\n    creating build\n    creating build/lib.linux-x86_64-3.8\n    creating build/lib.linux-x86_64-3.8/cffi\n    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi\n    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi\n    running build_ext\n    building '_cffi_backend' extension\n    creating build/temp.linux-x86_64-3.8\n    creating build/temp.linux-x86_64-3.8/c\n    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o\n    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory\n       15 | #include <ffi.h>\n          |          ^~~~~~~\n    compilation terminated.\n    error: command 'gcc' failed with exit status 1\n    ----------------------------------------\n    ERROR: Failed building wheel for cffi\n    Running setup.py clean for cffi\n  Failed to build cffi\n  Installing collected packages: setuptools, wheel, pycparser, cffi, semantic-version, typing-extensions, setuptools-rust\n      Running setup.py install for cffi: started\n      Running setup.py install for cffi: finished with status 'error'\n      ERROR: Command errored out with exit status 1:\n       command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-y7hxdoqg/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-cqcmhiwj/overlay --compile --install-headers /tmp/pip-build-env-cqcmhiwj/overlay/include/python3.8/cffi\n           cwd: /tmp/pip-install-1zk5v_9p/cffi/\n      Complete output (36 lines):\n      running install\n      running build\n      running build_py\n      creating build\n      creating build/lib.linux-x86_64-3.8\n      creating build/lib.linux-x86_64-3.8/cffi\n      copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi\n      copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi\n      running build_ext\n      building '_cffi_backend' extension\n      creating build/temp.linux-x86_64-3.8\n      creating build/temp.linux-x86_64-3.8/c\n      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o\n      c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory\n         15 | #include <ffi.h>\n            |          ^~~~~~~\n      compilation terminated.\n      error: command 'gcc' failed with exit status 1\n      ----------------------------------------\n  ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-1zk5v_9p/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-y7hxdoqg/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-cqcmhiwj/overlay --compile --install-headers /tmp/pip-build-env-cqcmhiwj/overlay/include/python3.8/cffi Check the logs for full command output.\n  WARNING: You are using pip version 20.0.2; however, version 22.3.1 is available.\n  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n  ----------------------------------------\n\u001b[0m\u001b[91mERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-cqcmhiwj/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '\"'\"'PyPy'\"'\"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.\n\u001b[0m\u001b[91mWARNING: You are using pip version 20.0.2; however, version 22.3.1 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n\u001b[0mRemoving intermediate container 4c40c0405416\n","stderr":"The command '/bin/sh -c pip install mlf-core' returned a non-zero code: 1\n"}}