{"repository":"https://github.com/jforman/binder","dockerfilePath":"Dockerfile","startTime":1672041833053,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/jforman/binder'...\n","error":null,"commit":"a158e984de2e58fd37bebfa51822a995da8c5819"},"originalBuild":{"startTimestamp":1672041833953,"endTimestamp":1672041862657,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t binder:latest -f /tmp/dinghy-analysis/jforman/binder/Dockerfile ."},"stdout":"Sending build context to Docker daemon  2.337MB\r\r\nStep 1/9 : FROM python:3-alpine\n ---> 18ccdc39ea28\nStep 2/9 : MAINTAINER Jeffrey Forman <code@jeffreyforman.net>\n ---> Running in b379db2b953e\nRemoving intermediate container b379db2b953e\n ---> f7d3b2077f97\nStep 3/9 : WORKDIR /code\n ---> Running in 0331fec8abc7\nRemoving intermediate container 0331fec8abc7\n ---> 6565f151cfeb\nStep 4/9 : COPY . /code/\n ---> 545e008a25e1\nStep 5/9 : RUN apk add --no-cache nsd build-base python3-dev libffi-dev openssl-dev libc-dev libxslt-dev mariadb-connector-c-dev   && pip install --upgrade pip   && pip install --no-cache-dir -r requirements.txt\n ---> Running in 3bf2855f57c9\nfetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz\nfetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz\n(1/40) Installing libgcc (12.2.1_git20220924-r4)\n(2/40) Installing libstdc++ (12.2.1_git20220924-r4)\n(3/40) Installing binutils (2.39-r2)\n(4/40) Installing libmagic (5.43-r0)\n(5/40) Installing file (5.43-r0)\n(6/40) Installing libgomp (12.2.1_git20220924-r4)\n(7/40) Installing libatomic (12.2.1_git20220924-r4)\n(8/40) Installing gmp (6.2.1-r2)\n(9/40) Installing isl25 (0.25-r0)\n(10/40) Installing mpfr4 (4.1.0-r0)\n(11/40) Installing mpc1 (1.2.1-r1)\n(12/40) Installing gcc (12.2.1_git20220924-r4)\n(13/40) Installing libstdc++-dev (12.2.1_git20220924-r4)\n(14/40) Installing musl-dev (1.2.3-r4)\n(15/40) Installing libc-dev (0.7.2-r3)\n(16/40) Installing g++ (12.2.1_git20220924-r4)\n(17/40) Installing make (4.3-r1)\n(18/40) Installing fortify-headers (1.1-r1)\n(19/40) Installing patch (2.7.6-r8)\n(20/40) Installing build-base (0.5-r3)\n(21/40) Installing linux-headers (5.19.5-r0)\n(22/40) Installing pkgconf (1.9.3-r0)\n(23/40) Installing libffi-dev (3.4.4-r0)\n(24/40) Installing libgpg-error (1.46-r1)\n(25/40) Installing libgcrypt (1.10.1-r0)\n(26/40) Installing libxml2 (2.10.3-r1)\n(27/40) Installing libxslt (1.1.37-r0)\n(28/40) Installing zlib-dev (1.2.13-r0)\n(29/40) Installing xz-dev (5.2.9-r0)\n(30/40) Installing libxml2-utils (2.10.3-r1)\n(31/40) Installing libxml2-dev (2.10.3-r1)\n(32/40) Installing libxslt-dev (1.1.37-r0)\n(33/40) Installing openssl-dev (3.0.7-r0)\n(34/40) Installing mariadb-connector-c (3.3.3-r0)\n(35/40) Installing mariadb-connector-c-dev (3.3.3-r0)\n(36/40) Installing libevent (2.1.12-r5)\n(37/40) Installing nsd (4.6.1-r0)\nExecuting nsd-4.6.1-r0.pre-install\n(38/40) Installing mpdecimal (2.5.1-r1)\n(39/40) Installing python3 (3.10.9-r1)\n(40/40) Installing python3-dev (3.10.9-r1)\nExecuting busybox-1.35.0-r29.trigger\nOK: 365 MiB in 77 packages\nRequirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (22.3.1)\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mCollecting cryptography\n  Downloading cryptography-38.0.4-cp36-abi3-musllinux_1_1_x86_64.whl (4.2 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 71.6 MB/s eta 0:00:00\nCollecting Django\n  Downloading Django-4.1.4-py3-none-any.whl (8.1 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 115.2 MB/s eta 0:00:00\nCollecting django-mysql\n  Downloading django_mysql-4.8.0-py3-none-any.whl (55 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 238.1 MB/s eta 0:00:00\nCollecting dnspython>=1.16.0\n  Downloading dnspython-2.2.1-py3-none-any.whl (269 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 219.0 MB/s eta 0:00:00\nCollecting Jinja2\n  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 269.5 MB/s eta 0:00:00\nCollecting lxml\n  Downloading lxml-4.9.2-cp311-cp311-musllinux_1_1_x86_64.whl (7.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 27.6 MB/s eta 0:00:00\nCollecting pybindxml>=0.7\n  Downloading pybindxml-0.7-py3-none-any.whl (3.9 kB)\nCollecting mysqlclient\n  Downloading mysqlclient-2.1.1.tar.gz (88 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.1/88.1 kB 79.6 MB/s eta 0:00:00\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting cffi>=1.12\n  Downloading cffi-1.15.1-cp311-cp311-musllinux_1_1_x86_64.whl (474 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.3/474.3 kB 169.8 MB/s eta 0:00:00\nCollecting asgiref<4,>=3.5.2\n  Downloading asgiref-3.6.0-py3-none-any.whl (23 kB)\nCollecting sqlparse>=0.2.2\n  Downloading sqlparse-0.4.3-py3-none-any.whl (42 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 166.3 MB/s eta 0:00:00\nCollecting MarkupSafe>=2.0\n  Downloading MarkupSafe-2.1.1.tar.gz (18 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting beautifulsoup4\n  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 260.7 MB/s eta 0:00:00\nCollecting pycparser\n  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 88.1 MB/s eta 0:00:00\nCollecting soupsieve>1.2\n  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)\nBuilding wheels for collected packages: mysqlclient, MarkupSafe\n  Building wheel for mysqlclient (setup.py): started\n  Building wheel for mysqlclient (setup.py): finished with status 'done'\n  Created wheel for mysqlclient: filename=mysqlclient-2.1.1-cp311-cp311-linux_x86_64.whl size=57133 sha256=6b3d8c9ffeda6de1ee3fd24aedebb65f649191061e3a18d2883eefd4f86be0e3\n  Stored in directory: /tmp/pip-ephem-wheel-cache-7dkl7icw/wheels/79/b2/17/a308360433f77818b9ddfd53121edb8148c0430b10c5012c83\n  Building wheel for MarkupSafe (setup.py): started\n  Building wheel for MarkupSafe (setup.py): finished with status 'done'\n  Created wheel for MarkupSafe: filename=MarkupSafe-2.1.1-cp311-cp311-linux_x86_64.whl size=15108 sha256=9831094acfe795331506b5188242819bc79af2c9d788e98afda9e544acd51bc0\n  Stored in directory: /tmp/pip-ephem-wheel-cache-7dkl7icw/wheels/96/ee/62/407c247ad088bcb67b530ba3ac1479058c58a651bd6bf09a1f\nSuccessfully built mysqlclient MarkupSafe\nInstalling collected packages: sqlparse, soupsieve, pycparser, mysqlclient, MarkupSafe, lxml, dnspython, asgiref, Jinja2, Django, cffi, beautifulsoup4, pybindxml, django-mysql, cryptography\nSuccessfully installed Django-4.1.4 Jinja2-3.1.2 MarkupSafe-2.1.1 asgiref-3.6.0 beautifulsoup4-4.11.1 cffi-1.15.1 cryptography-38.0.4 django-mysql-4.8.0 dnspython-2.2.1 lxml-4.9.2 mysqlclient-2.1.1 pybindxml-0.7 pycparser-2.21 soupsieve-2.3.2.post1 sqlparse-0.4.3\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mRemoving intermediate container 3bf2855f57c9\n ---> 0852f4ab69a2\nStep 6/9 : EXPOSE 8000\n ---> Running in 11abb02ae21c\nRemoving intermediate container 11abb02ae21c\n ---> 37b2cd50d6ff\nStep 7/9 : RUN [\"python\", \"manage.py\", \"makemigrations\", \"binder\"]\n ---> Running in 33652d268a0f\n\u001b[91mTraceback (most recent call last):\n  File \"/code/manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py\", line 446, in execute_from_command_line\n\u001b[0m\u001b[91m    utility.execute()\n  File \"/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py\", line 440, in execute\n\u001b[0m\u001b[91m    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/local/lib/python3.11/site-packages/django/core/management/base.py\", line 402, in run_from_argv\n\u001b[0m\u001b[91m    self.execute(*args, **cmd_options)\n  File \"/usr/local/lib/python3.11/site-packages/django/core/management/base.py\", line 443, in execute\n\u001b[0m\u001b[91m    self.check()\n  File \"/usr/local/lib/python3.11/site-packages/django/core/management/base.py\", line 475, in check\n\u001b[0m\u001b[91m    all_issues = checks.run_checks(\n                 ^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py\", line 88, in run_checks\n\u001b[0m\u001b[91m    new_errors = check(app_configs=app_configs, databases=databases)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py\", line 14, in check_url_config\n\u001b[0m\u001b[91m    return check_resolver(resolver)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py\", line 24, in check_resolver\n\u001b[0m\u001b[91m    return check_method()\n\u001b[0m\u001b[91m           ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py\", line 494, in check\n\u001b[0m\u001b[91m    for pattern in self.url_patterns:\n                   ^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/functional.py\", line 57, in __get__\n\u001b[0m\u001b[91m    res = instance.__dict__[self.name] = self.func(instance)\n                                         ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py\", line 715, in url_patterns\n\u001b[0m\u001b[91m    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/utils/functional.py\", line 57, in __get__\n\u001b[0m\u001b[91m    res = instance.__dict__[self.name] = self.func(instance)\n\u001b[0m\u001b[91m                                         ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py\", line 708, in urlconf_module\n\u001b[0m\u001b[91m    return import_module(self.urlconf_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n\u001b[0m\u001b[91m    return _bootstrap._gcd_import(name[level:], package, level)\n\u001b[0m\u001b[91m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"<frozen importlib._bootstrap>\", line 1206, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1178, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1149, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n\u001b[0m\u001b[91m  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n  File \"/code/binder/urls.py\", line 1, in <module>\n\u001b[0m\u001b[91m    from django.conf.urls import include, url\nImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.11/site-packages/django/conf/urls/__init__.py)\n\u001b[0mRemoving intermediate container 33652d268a0f\n","stderr":"The command 'python manage.py makemigrations binder' returned a non-zero code: 1\n"},"endTime":1672041862731}