{"repository":"https://github.com/jeshan/botostubs","dockerfilePath":"Dockerfile","startTime":1672040629341,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/jeshan/botostubs'...\n","error":null,"commit":"f908bed9ae8296be5b2597a5755fa54e34472394"},"originalBuild":{"startTimestamp":1672040631165,"endTimestamp":1672040734788,"error":null,"stdout":"Sending build context to Docker daemon  8.422MB\r\r\nStep 1/17 : FROM python:3.6-alpine\n ---> 3a9e80fa4606\nStep 2/17 : RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev tree curl\n ---> Running in dd0bce02b8dc\nfetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz\nfetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz\n(1/23) Upgrading libcrypto1.1 (1.1.1l-r7 -> 1.1.1s-r1)\n(2/23) Upgrading libssl1.1 (1.1.1l-r7 -> 1.1.1s-r1)\n(3/23) Installing brotli-libs (1.0.9-r5)\n(4/23) Installing nghttp2-libs (1.46.0-r0)\n(5/23) Installing libcurl (7.80.0-r5)\n(6/23) Installing curl (7.80.0-r5)\n(7/23) Installing libgcc (10.3.1_git20211027-r0)\n(8/23) Installing libstdc++ (10.3.1_git20211027-r0)\n(9/23) Installing binutils (2.37-r3)\n(10/23) Installing libgomp (10.3.1_git20211027-r0)\n(11/23) Installing libatomic (10.3.1_git20211027-r0)\n(12/23) Installing libgphobos (10.3.1_git20211027-r0)\n(13/23) Installing gmp (6.2.1-r1)\n(14/23) Installing isl22 (0.22-r0)\n(15/23) Installing mpfr4 (4.1.0-r0)\n(16/23) Installing mpc1 (1.2.1-r0)\n(17/23) Installing gcc (10.3.1_git20211027-r0)\n(18/23) Installing linux-headers (5.10.41-r0)\n(19/23) Installing pkgconf (1.8.0-r0)\n(20/23) Installing libffi-dev (3.4.2-r1)\n(21/23) Installing musl-dev (1.2.2-r7)\n(22/23) Installing openssl-dev (1.1.1s-r1)\n(23/23) Installing tree (1.8.0-r0)\nExecuting busybox-1.34.1-r3.trigger\nOK: 143 MiB in 55 packages\nRemoving intermediate container dd0bce02b8dc\n ---> 354bbf8e37cc\nStep 3/17 : WORKDIR /app\n ---> Running in 6cc9afd1eb89\nRemoving intermediate container 6cc9afd1eb89\n ---> 84e0b5f50f13\nStep 4/17 : RUN pip install pipenv\n ---> Running in caca8a75ccf2\nCollecting pipenv\n  Downloading pipenv-2022.4.8-py2.py3-none-any.whl (3.6 MB)\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)\nCollecting certifi\n  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)\nRequirement already satisfied: pip>=18.0 in /usr/local/lib/python3.6/site-packages (from pipenv) (21.2.4)\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (57.5.0)\nCollecting virtualenv\n  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)\nCollecting distlib<1,>=0.3.6\n  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\nCollecting platformdirs<3,>=2.4\n  Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)\nCollecting filelock<4,>=3.4.1\n  Downloading filelock-3.4.1-py3-none-any.whl (9.9 kB)\nCollecting importlib-metadata>=4.8.3\n  Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)\nCollecting importlib-resources>=5.4\n  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)\nCollecting zipp>=0.5\n  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)\nCollecting typing-extensions>=3.6.4\n  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)\nInstalling collected packages: zipp, typing-extensions, platformdirs, importlib-resources, importlib-metadata, filelock, distlib, virtualenv-clone, virtualenv, certifi, pipenv\nSuccessfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.4.1 importlib-metadata-4.8.3 importlib-resources-5.4.0 pipenv-2022.4.8 platformdirs-2.4.0 typing-extensions-4.1.1 virtualenv-20.17.1 virtualenv-clone-0.5.7 zipp-3.6.0\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0m\u001b[91mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n\u001b[0mRemoving intermediate container caca8a75ccf2\n ---> 9a0838ca15be\nStep 5/17 : COPY Pipfile* ./\n ---> dd099f7916a8\nStep 6/17 : RUN pipenv install --system\n ---> Running in 3df9eaf6ce74\nInstalling dependencies from Pipfile.lock (ca303a)...\nRemoving intermediate container 3df9eaf6ce74\n ---> 179f419ee368\nStep 7/17 : RUN pip install --upgrade boto3\n ---> Running in 7b968d48cf4a\nRequirement already satisfied: boto3 in /usr/local/lib/python3.6/site-packages (1.11.9)\nCollecting boto3\n  Downloading boto3-1.23.10-py3-none-any.whl (132 kB)\nCollecting s3transfer<0.6.0,>=0.5.0\n  Downloading s3transfer-0.5.2-py3-none-any.whl (79 kB)\nRequirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.6/site-packages (from boto3) (0.9.4)\nCollecting botocore<1.27.0,>=1.26.10\n  Downloading botocore-1.26.10-py3-none-any.whl (8.8 MB)\nRequirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.6/site-packages (from botocore<1.27.0,>=1.26.10->boto3) (2.8.1)\nRequirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.6/site-packages (from botocore<1.27.0,>=1.26.10->boto3) (1.25.8)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.27.0,>=1.26.10->boto3) (1.14.0)\nInstalling collected packages: botocore, s3transfer, boto3\n  Attempting uninstall: botocore\n    Found existing installation: botocore 1.14.9\n    Uninstalling botocore-1.14.9:\n      Successfully uninstalled botocore-1.14.9\n  Attempting uninstall: s3transfer\n    Found existing installation: s3transfer 0.3.2\n    Uninstalling s3transfer-0.3.2:\n      Successfully uninstalled s3transfer-0.3.2\n  Attempting uninstall: boto3\n    Found existing installation: boto3 1.11.9\n    Uninstalling boto3-1.11.9:\n      Successfully uninstalled boto3-1.11.9\nSuccessfully installed boto3-1.23.10 botocore-1.26.10 s3transfer-0.5.2\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0m\u001b[91mWARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n\u001b[0mRemoving intermediate container 7b968d48cf4a\n ---> 6cd297e34ae2\nStep 8/17 : COPY test-data test-data\n ---> 1bc27e269d93\nStep 9/17 : COPY post-release-data.py test_pytestcleanup_cases.py conftest.py pythonic.py main.py release.sh README.md setup.py ./\n ---> 2bff6e196556\nStep 10/17 : ENV AWS_DEFAULT_REGION=us-east-1\n ---> Running in f6d963eb3182\nRemoving intermediate container f6d963eb3182\n ---> a8e0f454fee8\nStep 11/17 : RUN export AWS_ACCESS_KEY_ID=FAKE AWS_SECRET_ACCESS_KEY=FAKE &&   pytest --cov-report term-missing --cov=main -vv -s --show-progress test_pytestcleanup_cases.py\n ---> Running in 2068851cc8e7\n============================= test session starts ==============================\nplatform linux -- Python 3.6.15, pytest-5.3.4, py-1.8.1, pluggy-0.13.1 -- /usr/local/bin/python\ncachedir: .pytest_cache\nrootdir: /app\nplugins: cov-2.8.1, progress-1.2.1\ncollecting ... \u001b[91m2022-12-26 07:45:15.003 | DEBUG    | pytest_cleanup.constants:get_test_dir:18 - Will place test_pytestcleanup_cases.py under /app\n\u001b[0m\u001b[91m2022-12-26 07:45:15.004 | INFO     | pytest_cleanup.recorder:__init__:238 - creating instance of recorder\n\u001b[0mcollected 61 items\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes0] PASSED\n_ 1 of 61 completed, 1 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes1] PASSED\n_ 2 of 61 completed, 2 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes2] PASSED\n_ 3 of 61 completed, 3 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes3] PASSED\n_ 4 of 61 completed, 4 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes4] PASSED\n_ 5 of 61 completed, 5 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes5] PASSED\n_ 6 of 61 completed, 6 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes6] PASSED\n_ 7 of 61 completed, 7 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes7] PASSED\n_ 8 of 61 completed, 8 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes8] PASSED\n_ 9 of 61 completed, 9 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-append_to_shapes9] PASSED\n_ 10 of 61 completed, 10 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_doc_str0] PASSED\n_ 11 of 61 completed, 11 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_doc_str1] PASSED\n_ 12 of 61 completed, 12 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_doc_str2] PASSED\n_ 13 of 61 completed, 13 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_doc_str3] PASSED\n_ 14 of 61 completed, 14 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_doc_str4] PASSED\n_ 15 of 61 completed, 15 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_method_signature0] PASSED\n_ 16 of 61 completed, 16 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_method_signature1] PASSED\n_ 17 of 61 completed, 17 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_method_signature2] PASSED\n_ 18 of 61 completed, 18 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_method_signature3] PASSED\n_ 19 of 61 completed, 19 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_method_signature4] PASSED\n_ 20 of 61 completed, 20 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_paginator_str0] PASSED\n_ 21 of 61 completed, 21 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_paginator_str1] PASSED\n_ 22 of 61 completed, 22 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_paginator_str2] PASSED\n_ 23 of 61 completed, 23 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_paginator_str3] PASSED\n_ 24 of 61 completed, 24 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_paginator_str4] PASSED\n_ 25 of 61 completed, 25 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_list0] PASSED\n_ 26 of 61 completed, 26 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_list1] PASSED\n_ 27 of 61 completed, 27 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_list2] PASSED\n_ 28 of 61 completed, 28 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_list3] PASSED\n_ 29 of 61 completed, 29 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_list4] PASSED\n_ 30 of 61 completed, 30 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_name0] PASSED\n_ 31 of 61 completed, 31 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_name1] PASSED\n_ 32 of 61 completed, 32 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_name2] PASSED\n_ 33 of 61 completed, 33 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_name3] PASSED\n_ 34 of 61 completed, 34 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_param_name4] PASSED\n_ 35 of 61 completed, 35 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_waiter_str0] PASSED\n_ 36 of 61 completed, 36 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_waiter_str1] PASSED\n_ 37 of 61 completed, 37 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_waiter_str2] PASSED\n_ 38 of 61 completed, 38 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_waiter_str3] PASSED\n_ 39 of 61 completed, 39 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-get_waiter_str4] PASSED\n_ 40 of 61 completed, 40 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_actions0] PASSED\n_ 41 of 61 completed, 41 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_actions1] PASSED\n_ 42 of 61 completed, 42 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_actions2] PASSED\n_ 43 of 61 completed, 43 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_actions3] PASSED\n_ 44 of 61 completed, 44 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_actions4] PASSED\n_ 45 of 61 completed, 45 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource0] PASSED\n_ 46 of 61 completed, 46 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource1] PASSED\n_ 47 of 61 completed, 47 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource2] PASSED\n_ 48 of 61 completed, 48 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource3] PASSED\n_ 49 of 61 completed, 49 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource4] PASSED\n_ 50 of 61 completed, 50 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_actions0] PASSED\n_ 51 of 61 completed, 51 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_actions1] PASSED\n_ 52 of 61 completed, 52 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_actions2] PASSED\n_ 53 of 61 completed, 53 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_actions3] PASSED\n_ 54 of 61 completed, 54 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_actions4] PASSED\n_ 55 of 61 completed, 55 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_waiters0] PASSED\n_ 56 of 61 completed, 56 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_waiters1] PASSED\n_ 57 of 61 completed, 57 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_waiters2] PASSED\n_ 58 of 61 completed, 58 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_waiters3] PASSED\n_ 59 of 61 completed, 59 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_sub_waiters4] PASSED\n_ 60 of 61 completed, 60 Pass, 0 Fail, 0 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_async_test_cases[fn0-args0-kwargs0-expected0] SKIPPED\n_ 61 of 61 completed, 60 Pass, 0 Fail, 1 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _\n\n=============================== warnings summary ===============================\n/usr/local/lib/python3.6/site-packages/_pytest/mark/structures.py:327\n  /usr/local/lib/python3.6/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html\n    PytestUnknownMarkWarning,\n\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource0]\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource1]\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource2]\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource3]\ntest_pytestcleanup_cases.py::test_pytest_cleanup_sync_test_cases[main-print_resource4]\n  /usr/local/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/\n    warnings.warn(warning, PythonDeprecationWarning)\n\n-- Docs: https://docs.pytest.org/en/latest/warnings.html\n\n---------- coverage: platform linux, python 3.6.15-final-0 -----------\nName      Stmts   Miss  Cover   Missing\n---------------------------------------\nmain.py     248    124    50%   55, 63, 67-68, 92, 98, 114-121, 134-144, 166, 184-189, 196, 204-212, 216-250, 290-293, 297-313, 317-337, 341-355, 360-365, 369-371, 375-377, 381\n\n================== 60 passed, 1 skipped, 6 warnings in 1.47s ===================\nRemoving intermediate container 2068851cc8e7\n ---> 313718587683\nStep 12/17 : RUN mkdir -p botostubs/botostubs\n ---> Running in e57910ce0317\nRemoving intermediate container e57910ce0317\n ---> 5def0420f3d3\nStep 13/17 : RUN cp -r test_pytestcleanup_cases.py conftest.py setup.py README.md release.sh botostubs/\n ---> Running in 3ecb8a3b2a9d\nRemoving intermediate container 3ecb8a3b2a9d\n ---> 122ae759b5ca\nStep 14/17 : RUN touch botostubs/botostubs/py.typed\n ---> Running in c0daf8158844\nRemoving intermediate container c0daf8158844\n ---> 44ba87b6d206\nStep 15/17 : RUN export AWS_ACCESS_KEY_ID=FAKE AWS_SECRET_ACCESS_KEY=FAKE && time python main.py > botostubs/botostubs/__init__.py\n ---> Running in 4b24f004ac39\n\u001b[91m/usr/local/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/\n  warnings.warn(warning, PythonDeprecationWarning)\n\u001b[0m\u001b[91mreal\t0m 12.39s\n\u001b[0m\u001b[91muser\t0m 10.60s\nsys\t0m 1.72s\n\u001b[0mRemoving intermediate container 4b24f004ac39\n ---> 31bdd2a37bea\nStep 16/17 : WORKDIR botostubs\n ---> Running in 698cc0ec7628\nRemoving intermediate container 698cc0ec7628\n ---> c81a5ffba8d0\nStep 17/17 : ENTRYPOINT [\"./release.sh\"]\n ---> Running in a933eb3fab1d\nRemoving intermediate container a933eb3fab1d\n ---> a4a0e75fd706\nSuccessfully built a4a0e75fd706\nSuccessfully tagged botostubs:latest\n","stderr":"","imageSize":446723164},"repair":{"violations":[],"repairedDockerfile":"FROM python:3.6-alpine\n\nRUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev tree curl\n\nWORKDIR /app\n\nRUN pip install pipenv\n\nCOPY Pipfile* ./\n\nRUN pipenv install --system\n\nRUN pip install --upgrade boto3\n\nCOPY test-data test-data\nCOPY post-release-data.py test_pytestcleanup_cases.py conftest.py pythonic.py main.py release.sh README.md setup.py ./\n\nENV AWS_DEFAULT_REGION=us-east-1\n\nRUN export AWS_ACCESS_KEY_ID=FAKE AWS_SECRET_ACCESS_KEY=FAKE && \\\n  pytest --cov-report term-missing --cov=main -vv -s --show-progress test_pytestcleanup_cases.py\n\nRUN mkdir -p botostubs/botostubs\n\nRUN cp -r test_pytestcleanup_cases.py conftest.py setup.py README.md release.sh botostubs/\nRUN touch botostubs/botostubs/py.typed\nRUN export AWS_ACCESS_KEY_ID=FAKE AWS_SECRET_ACCESS_KEY=FAKE && time python main.py > botostubs/botostubs/__init__.py\n\nWORKDIR botostubs\nENTRYPOINT [\"./release.sh\"]\n"},"endTime":1672040735385}