{"repository":"https://github.com/canada-nyc/django-dumper","dockerfilePath":"Dockerfile","startTime":1672223399314,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/canada-nyc/django-dumper'...\n","error":null,"commit":"d5fa653c28902c413718335e7da94661d1fbc213"},"originalBuild":{"startTimestamp":1672223400154,"endTimestamp":1672223405694,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t django-dumper:latest -f /tmp/dinghy-analysis/canada-nyc/django-dumper/Dockerfile ."},"stdout":"Sending build context to Docker daemon  170.5kB\r\r\nStep 1/5 : FROM python:3\n ---> 75cc8d87cc34\nStep 2/5 : RUN mkdir -p /usr/src/app\n ---> Running in ae7667714852\nRemoving intermediate container ae7667714852\n ---> ac406fe4eac6\nStep 3/5 : WORKDIR /usr/src/app\n ---> Running in a7b397597838\nRemoving intermediate container a7b397597838\n ---> 8ca8a770b686\nStep 4/5 : COPY . /usr/src/app\n ---> 3f53dc924fd8\nStep 5/5 : RUN pip install -e . -r requirements-dev.txt\n ---> Running in 809c3e0f7cdc\nObtaining file:///usr/src/app\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting django-discover-runner==1.0\n  Downloading django_discover_runner-1.0-py2.py3-none-any.whl (12 kB)\nCollecting mock==1.0.1\n  Downloading mock-1.0.1.zip (861 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 861.9/861.9 kB 32.6 MB/s eta 0:00:00\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting distribute\n  Downloading distribute-0.7.3.zip (145 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.4/145.4 kB 12.5 MB/s eta 0:00:00\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'error'\n\u001b[91m  error: subprocess-exited-with-error\n  \n  × python setup.py egg_info did not run successfully.\n  │ exit code: 1\n  ╰─> [17 lines of output]\n      Traceback (most recent call last):\n        File \"<string>\", line 2, in <module>\n        File \"<pip-setuptools-caller>\", line 14, in <module>\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/setuptools/__init__.py\", line 2, in <module>\n          from setuptools.extension import Extension, Library\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/setuptools/extension.py\", line 5, in <module>\n          from setuptools.dist import _get_unpatched\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/setuptools/dist.py\", line 7, in <module>\n          from setuptools.command.install import install\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/setuptools/command/__init__.py\", line 8, in <module>\n          from setuptools.command import install_scripts\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/setuptools/command/install_scripts.py\", line 3, in <module>\n          from pkg_resources import Distribution, PathMetadata, ensure_directory\n        File \"/tmp/pip-install-yizgf6u_/distribute_29532a384f944d69a27f7be6ce5d9f10/pkg_resources.py\", line 1518, in <module>\n          register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n      AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91merror: metadata-generation-failed\n\n× Encountered error while generating package metadata.\n╰─> See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\n\u001b[0mRemoving intermediate container 809c3e0f7cdc\n","stderr":"The command '/bin/sh -c pip install -e . -r requirements-dev.txt' returned a non-zero code: 1\n"},"endTime":1672223405766}