{
  "startTime": 1674254221705,
  "endTime": 1674254222695,
  "originalSmells": [
    {
      "rule": "pipUseNoCacheDir",
      "position": {
        "lineStart": 18,
        "lineEnd": 18,
        "columnStart": 4,
        "columnEnd": 36
      }
    },
    {
      "rule": "aptGetInstallUseNoRec",
      "position": {
        "lineStart": 2,
        "lineEnd": 5,
        "columnStart": 22,
        "columnEnd": 13
      }
    }
  ],
  "repairedSmells": [],
  "repairedDockerfile": "FROM ubuntu:16.04\n\nRUN apt-get update && apt-get install --no-install-recommends -y \\\n  xinetd \\\n  python3-pip \\\n  python3-dev \\\n  && rm -rf /var/lib/apt/lists/*\n\nRUN mkdir /ctf\nWORKDIR /ctf\nRUN useradd -M -d /ctf ctf\n\nRUN echo \"Connection blocked\" > /etc/banner_fail\nCOPY ctf.xinetd /etc/xinetd.d/ctf\nCOPY ./src /ctf/\n\nRUN chown -R ctf:ctf /ctf && chmod -R 770 /ctf\nRUN su ctf -c \"pip3 install pycryptodome==3.4.3\"\nRUN pip3 install --no-cache-dir pycryptodome==3.4.3\n\nRUN chown -R root:ctf /ctf && \\\n  chmod -R 750 /ctf\n\n\nENTRYPOINT []\nCMD [\"/usr/sbin/xinetd\", \"-dontfork\"]\n\nEXPOSE 9999\n"
}