{"repository":"https://github.com/nrel/ditto","dockerfilePath":"Dockerfile","startTime":1673246455423,"endTime":1673246469083,"clone":{"startTime":1673246455481,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/nrel/ditto'...\n","error":null,"endTime":1673246456731,"commit":"8cc2880b4f48715321cb00f382cb1d5b6be5dc98"},"originalBuild":{"startTime":1673246456851,"endTime":1673246469018,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t ditto:latest -f /tmp/dinghy-analysis/nrel/ditto/Dockerfile ."},"stdout":"Sending build context to Docker daemon   21.7MB\r\r\nStep 1/7 : FROM python:3.6-slim\n3.6-slim: Pulling from library/python\na2abf6c4d29d: Pulling fs layer\n625294dad115: Pulling fs layer\n838e3a5a04bf: Pulling fs layer\ne93b4e59b689: Pulling fs layer\nc4401b8c7f9e: Pulling fs layer\nc4401b8c7f9e: Waiting\n838e3a5a04bf: Download complete\ne93b4e59b689: Download complete\n625294dad115: Download complete\nc4401b8c7f9e: Verifying Checksum\nc4401b8c7f9e: Download complete\na2abf6c4d29d: Pull complete\n625294dad115: Pull complete\n838e3a5a04bf: Pull complete\ne93b4e59b689: Pull complete\nc4401b8c7f9e: Pull complete\nDigest: sha256:2cfebc27956e6a55f78606864d91fe527696f9e32a724e6f9702b5f9602d0474\nStatus: Image is up to date for python:3.6-slim\n ---> c1e40b69532f\nStep 2/7 : COPY ./ $HOME/ditto\n ---> 419396d5aa0c\nStep 3/7 : WORKDIR $HOME/ditto\n ---> Running in 63e3d5dbe9ca\nRemoving intermediate container 63e3d5dbe9ca\n ---> c1e82f244ac2\nStep 4/7 : RUN python -m pip install --upgrade pip && pip install -e .[all] && pip install pytest\n ---> Running in 78823e0d7c2c\nRequirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.2.4)\nCollecting pip\n  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)\nInstalling collected packages: pip\n  Attempting uninstall: pip\n    Found existing installation: pip 21.2.4\n    Uninstalling pip-21.2.4:\n      Successfully uninstalled pip-21.2.4\nSuccessfully installed pip-21.3.1\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mObtaining file:///ditto\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting click~=8.0.4\n  Downloading click-8.0.4-py3-none-any.whl (97 kB)\nCollecting future~=0.18.2\n  Downloading future-0.18.2.tar.gz (829 kB)\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nCollecting networkx~=2.5.1\n  Downloading networkx-2.5.1-py3-none-any.whl (1.6 MB)\nCollecting six~=1.16.0\n  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\n\u001b[91mERROR: Could not find a version that satisfies the requirement traitlets~=5.1.1 (from ditto-py[all]) (from versions: 0.0.1, 0.0.2, 4.0.0.dev0, 4.0.0, 4.1.0b1, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.3.0b1, 4.3.0, 4.3.1, 4.3.2, 4.3.3.dev0, 4.3.3)\n\u001b[0m\u001b[91mERROR: No matching distribution found for traitlets~=5.1.1\n\u001b[0mRemoving intermediate container 78823e0d7c2c\n","stderr":"The command '/bin/sh -c python -m pip install --upgrade pip && pip install -e .[all] && pip install pytest' returned a non-zero code: 1\n"}}